apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pass-web
  namespace: pai4
  labels:
    app: my-pass-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pass-web
  template:
    metadata:
      labels:
        app: my-pass-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: my-pass-web:staging
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
